[project]
name = "teknokent-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "brotli>=1.1.0",
    "scrapy>=2.13.3",
    "scrapy-playwright>=0.0.44",
    "scrapy-user-agents>=0.1.1",
]
